version: '3.8'

services:
  mongo:
    image: mongo:4.2.8
    env_file: ./.env.local
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PWD}'
    volumes:
      - mongodb_data_container:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    env_file: ./.env.local
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${MONGO_USER}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${MONGO_PWD}'

volumes:
  mongodb_data_container:
